---
name: Publish
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - develop
jobs:
  msys2-mingw:
    name: Publish Mingw 64
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/dmiget
          releases-only: true
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git dos2unix mingw-w64-x86_64-gcc automake autoconf make pkgconf
            gettext-devel libtool xz
      - name: CI-Build
        run: |
          dos2unix PKGBUILD.mingw
          makepkg BUILDDIR=/tmp/pkg -f -p PKGBUILD.mingw
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "*.pkg.tar.zst"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
  msvc:
    runs-on: windows-latest
    name: Publish MSVC 64
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/dmiget
          releases-only: true
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: CI-Build
        run: |
          nmake -f win\Makefile.msc
          xcopy /s /i /y src\include\smbios\*.h include\smbios
          7z a msvc-dmiget-x86_64.zip .\lib .\bin .\include
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "msvc-dmiget-x86_64.zip"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true
  python:
    runs-on: windows-latest
    name: Publish Windows python
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/dmiget
          releases-only: true
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Build installer
        run: python setup.py bdist_wininst
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "dist/*.exe"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true

