name: publish
on:
  push:
    branches: [ "develop" ]

jobs:
  python:
    runs-on: ubuntu-latest
    name: Publish python module
    environment:
      name: pypi
      url: https://pypi.org/p/smbios
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing      
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Install Python Dependencies
        run: pip install meson ninja build twine
      - name: Build package
        run: python3 -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        