name: publish
on:
  push:
    branches: [ "develop" ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: Publish to pypi
    environment:
      name: pypi
      url: https://pypi.org/p/smbios
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing      
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
      - name: Install Python Dependencies
        run: pip install meson ninja build
      - name: Build package
        run: python3 -m build
      - name: Publishing package
        uses: pypa/gh-action-pypi-publish@release/v1
