---
name: Publish
on:
  push:
    branches:
      - python
jobs:
  python:
    runs-on: ubuntu-latest
    name: Publish Python package
    steps:
      - uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/dmiget
          releases-only: true
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Build installer
        run: python setup.py sdist

