---
name: Publish
on:
  push:
    branches:
      - python
jobs:
  python:
    runs-on: ubuntu-latest
    name: Publish Python package
    environment:
      name: testpypi
      url: https://pypi.org/p/smbios
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing  
    steps:
      - uses: actions/checkout@v3
      - name: Build installer
        run: python setup.py sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
